#!/bin/bash
#
# Runs server for development.
#
# First time, call:
#   bash etc/run.sh install
#
# This installs conda environment "slicops", where it installs nodejs,
# python, and slicops. Also builds apptainer image (slicops.sif) if it
# can't find $SLICOPS_APPTAINER_SIF.
#
# When developing, start three servers:
#   bash etc/run.sh sim
#   bash etc/run.sh vue
#   bash etc/run.sh api
set -eou pipefail
shopt -s nullglob

_root_dir=$(cd "$(dirname "$0")/.." && pwd)
_run_dir=$_root_dir/run
_docker_image=docker://radiasoft/slicops
declare -A _port_map=(
    [api]=0
    [repeater]=2
    [server]=3
    [vue]=1
)
_bashrc=$_run_dir/bashrc.sh
_python_version=3.12.11
_sif=${SLICOPS_APPTAINER_SIF:-$_run_dir/slicops.sif}
_sim_dir=/home/vagrant/.local/epics/extensions/synApps/support/areaDetector-R3-12-1/ADSimDetector/iocs/simDetectorIOC/iocBoot/iocSimDetector
_vue_dir=$_root_dir/ui
_start_msg="To develop, start the servers in this order in separate terminals:
bash etc/run.sh sim # sim-detector for DEV_CAMERA
bash etc/run.sh vue # vue server for javascript
bash etc/run.sh api # tornado for business logic and main server"

_dispatch_op() {
    declare op=$1
    declare -a args=( "${@:2}" )
    declare f=_op_$op
    if [[ $(type -t "$f") != 'function' ]]; then
        _err "invalid op=$op
usage: bash ${BASH_SOURCE[0]} <op>
where <op> is one of:
$(compgen -A function _op_ | sed -e 's/^_op_//')

$_start_msg"
    fi
    "$f" "${args[@]}"
}

_env_base_port() {
    declare p=${SLICOPS_BASE_PORT:-}
    if [[ $p ]]; then
        _env_base_port_assert "$p"
        return
    fi
    _env_bashrc
}

_env_base_port_assert() {
    declare port=$1
    declare file=${2:-}
    if [[ ! $port =~ ^[0-9]+$ ]] || (( port <= 5000 )); then
        _err "SLICOPS_BASE_PORT=$port must be an integer above 5000${file:+

rm $file
and run this script again}"
    fi
}

_env_bashrc() {
    if [[ ! -r $_bashrc ]]; then
        _env_bashrc_create
    fi
    source "$_bashrc"
    _env_base_port_assert "${SLICOPS_BASE_PORT:-}" "$_bashrc"
}

_env_bashrc_create() {
    declare p=$(_port_find)
    if [[ ! $p ]]; then
        return 1
    fi
    cat <<EOF_cat > "$_bashrc"
#!/bin/bash
# Configuration dynamically generated by etc/run.sh.
# Copy to ~/.bashrc, source ~/.bashrc, and remove this file.
export SLICOPS_BASE_PORT=$p
EOF_cat
    _msg "Created $_bashrc
which sets:

export SLICOPS_BASE_PORT=$p

You can also put this value in your ~/.bashrc.
"
}

_env_check() {
    if [[ ! -d $_run_dir ]]; then
        mkdir -p "$_run_dir"
    fi
    _env_base
    _env_conda_activate
    _env_vue
    # Longest so last so people can get a coffee
    _env_sif
    cd "$_run_dir"
    _env_base_port
}

_env_base() {
    if ! type -t apptainer &> /dev/null; then
        _err 'apptainer not installed; please install:

curl -s https://raw.githubusercontent.com/apptainer/apptainer/main/tools/install-unprivileged.sh | \
    bash -s - ~/apptainer
cat >> ~/.bashrc <<'"'EOF'"'
if [[ ! :$PATH: =~ :$HOME/apptainer/bin: ]]; then
    PATH=$HOME/apptainer/bin/apptainer:$PATH
fi
EOF
source ~/.bashrc
'
    fi
    if ! type -t conda &> /dev/null; then
        _err 'conda not installed; please install:

wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O x.sh
bash x.sh
rm x.sh
source ~/.bashrc
'
    fi
}

_env_conda_activate() {
    _source_bashrc
    if ! conda activate slicops &> /dev/null; then
        _msg 'Creating conda environment slicops'
        conda create --quiet --yes --name slicops
        if ! conda activate slicops; then
            _err 'unable to activate slicops after creating'
        fi
    fi
    _env_conda_package python "$_python_version"
    # Just in case
    _env_conda_package pip
    _env_conda_package nodejs
    declare -a x=( $(conda info | grep 'active env location') )
    _conda_dir=${x[-1]}
    _env_pip_package pykern
    _env_pip_package slicops
}

_env_conda_package() {
    declare name=$1
    declare version=${2:-}
    if ! conda list | grep -q "^$name "; then
        declare p=$name${version:+=$version}
        _msg "Installing $p"
        conda install --quiet --yes "$p"
    fi
}

_env_pip_not_ok() {
    declare name=$1
    declare -a f=( $(pip show "$name" | grep ^Location: 2>/dev/null) )
    if [[ $f && ${f[-1]} =~ ^$_conda_dir ]]; then
        return
    fi
    # For error msg
    echo "${f[-1]}"
}

_env_pip_package() {
    declare name=$1
    if [[ ! $(_env_pip_not_ok "$name") ]]; then
        return
    fi
    _msg "Installing $name"
    case $name  in
        slicops)
            pip install --quiet --yes -e .
            ;;
        pykern)
            _env_pip_package_rs "$name"
            ;;
        *)
            _err "_env_pip_location: pkg=$name unsupported"
            ;;
    esac
    declare l=$(_env_pip_not_ok "$name")
    if [[ $l ]]; then
        _err "pip installed pkg=$name in wrong location=$l"
    fi
}

_env_pip_package_rs() {
    declare name=$1
    declare p=$PWD
    cd ..
    if [[ -d $name ]]; then
        cd $name
        git pull --quiet
    else
        git clone --quiet https://github.com/radiasoft/$name
        cd $name
    fi
    pip install --quiet --yes -e .
    cd "$p" &> /dev/null
}

_env_sif() {
    if [[ -r $_sif ]]; then
        return
    fi
    _msg "Building $_sif from $_docker_image. This will take about 45 minutes..."
    declare f=$_run_dir/image.log
    if ! TMPDIR=$_run_dir apptainer build --quiet "$_sif" $_docker_image &> "$f"; then
        tail --lines=50 "$f"
        _err "build image=$_sif failed. Full log: $f"
    fi
    rm -f "$f"
}

_env_vue() {
    if [[ -d $_vue_dir/node_modules/vite ]]; then
        return
    fi
    _msg 'Installing ui/node_modules'
    cd "$_vue_dir"
    npm install --quiet
}

_epics_env() {
    declare assert=${1:-}
    declare s=$(_port server $assert)
    declare r=$(_port repeater $assert)
    if ! [[ $s && $r ]]; then
        # Used in subshell and error already printed
        return 1
    fi
    echo "EPICS_CA_REPEATER_PORT=$r EPICS_CA_SERVER_PORT=$s EPICS_CA_AUTO_ADDR_LIST=NO EPICS_CA_ADDR_LIST=127.0.0.1:$s"
}

_err() {
    _msg "$@"
    exit 1
}

_log() {
    _msg $(date +%H%M%S) "$@"
}

_main() {
    declare op=${1:-<not set>}
    _env_check
    _dispatch_op "$op" "${@:2}"
}

_msg() {
    echo "$*" 1>&2
}

_op_api() {
    declare e=$(_epics_env)
    declare p=$(_port api assert)
    declare v=$(_port vue)
    if ! [[ $e && $p && $v ]]; then
        return 1
    fi
    _msg "
Ignore error about caRepeater couldn't be located.

Connect to: http://localhost:$p
"
    # not in quotes, because eval
    eval $e SLICOPS_CONFIG_UI_API_VUE_PORT=$v \
         exec slicops service ui_api --tcp-port="$p"
}

_op_install() {
    _msg "Everything installed.

$_start_msg"
}

_op_sim() {
    declare e=$(_epics_env assert)
    if [[ ! $e ]]; then
        return 1
    fi
    exec apptainer run --containall "$_sif" bash -c "$e slicops epics sim-detector --ioc-sim-detector-dir='$_sim_dir'"
}

_op_vue() {
    cd "$_vue_dir"
    declare v=$(_port vue assert)
    if [[ ! $v ]]; then
        return 1
    fi
    SLICOPS_VUE_PORT=$v exec npm run dev
}

_port() {
    declare name=${1:-}
    declare assert=${2:-}
    declare p=${_port_map[$name]}
    if [[ ! $p ]]; then
        _err "assertion error: _port missing port arg=${1:-<missing arg>}"
    fi
    p=$(( SLICOPS_BASE_PORT + p ))
    if [[ $assert ]] && ! _port_check "$p"; then
        _err "port=$p in use; is service=$name already running? Or, choose a different SLICOPS_BASE_PORT=$SLICOPS_BASE_PORT"
    fi
    echo "$p"
}

_port_check() {
    declare num=$1
    declare count=${2:-1}
    declare i
    for i in $(seq 0 $(( count - 1)) ); do
        if ss --tcp --udp --listening --numeric | grep -q ":$(( num + i ))"; then
            return 1
        fi
    done
}

_port_find() {
    declare -i start=$(( $(id -u) % 10000 + 10000 ))
    declare i
    # POSIT: does not need more than 10 ports
    for p in $(seq $start 10 $(( start + 90 )) );  do
        #TODO(robnagler) 4 should be a constant
        if _port_check "$p" 4; then
            echo "$p"
            return
        fi
    done
    # Should not happen
    _err 'could not find an open port; Set SLICOPS_BASE_PORT manually in ~/.bashrc'
}

_source_bashrc() {
    set +eou pipefail
    shopt -u nullglob
    source ~/.bashrc
    set -eou pipefail
    shopt -s nullglob
}

_main "$@"
